# Generated by Django 5.0.6 on 2024-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialorganization',
            name='phone',
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='financialorganization',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='financialorganization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
    ]
