# Generated by Django 5.0.6 on 2024-05-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0002_remove_financialorganization_phone_and_more'),
        ('fin_app', '0003_auto_20240509_2236'),
    ]

    operations = [
    ]
